/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bilibili: typeof import('./src/components/DetailPage/live/Bilibili.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    LanguageSetting: typeof import('./src/components/DetailPage/LanguageSetting.vue')['default']
    LeftMenu: typeof import('./src/components/left/LeftMenu.vue')['default']
    LiveSetting: typeof import('./src/components/DetailPage/LiveSetting.vue')['default']
    MainPage: typeof import('./src/components/MainPage.vue')['default']
    Navigator: typeof import('./src/components/DetailPage/navigator/Navigator.vue')['default']
    Overall: typeof import('./src/components/DetailPage/live/Overall.vue')['default']
    ProxySetting: typeof import('./src/components/DetailPage/live/overall/ProxySetting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Youtube: typeof import('./src/components/DetailPage/live/Youtube.vue')['default']
  }
}
